[project]
name = "todos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.11",
    "logfire[fastapi,system-metrics]>=3.9.0",
    "tinydb>=4.8.2",
    "upstash-redis>=1.3.0",
]
